# Generated by Django 3.1.7 on 2021-03-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('published_date', models.CharField(blank=True, max_length=80)),
                ('avarage_rating', models.CharField(blank=True, max_length=80)),
                ('ratings_count', models.FileField(blank=True, null=True, upload_to='sounds/')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='sounds/')),
                ('authors', models.ManyToManyField(related_name='authors', to='books.Authors')),
                ('categories', models.ManyToManyField(related_name='categories', to='books.Categories')),
            ],
        ),
    ]
