# Generated by Django 3.1.7 on 2021-03-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210324_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
