# Generated by Django 3.1.7 on 2021-03-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210325_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avarage_rating',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
