# Generated by Django 3.1.7 on 2021-03-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210325_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
