# Generated by Django 3.1.7 on 2021-03-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210326_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avarage_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
